In [9]:
import numpy as np

In [2]:
def findMaxFullGrid(grid): 
    num_rows = len(grid)
    num_cols = len(grid[0]) 
  
    S = [[0 for k in range(num_cols)] for l in range(num_rows)] 

    for i in range(1, num_rows): 
        for j in range(1, num_cols): 
            if (grid[i][j] != 0): 
                S[i][j] = min(S[i][j-1], S[i-1][j], 
                            S[i-1][j-1]) + 1
            else: 
                S[i][j] = 0

    max_of_s = S[0][0] 
    max_i = 0
    max_j = 0
    for i in range(num_rows): 
        for j in range(num_cols): 
            if (max_of_s < S[i][j]): 
                max_of_s = S[i][j] 
                max_i = i 
                max_j = j 
  
    return max_i-max_of_s+1, max_i, max_j-max_of_s+1, max_j

def assign_lighting(grid):
    lighting = np.zeros(grid.shape)
    return lighting


In [3]:
grid = [[0,0,0,0,0,0,1,1],
        [0,0,0,0,1,1,1,1],
        [0,1,1,1,1,1,1,1],
        [1,1,1,1,1,1,1,1],
        [1,1,1,1,1,1,1,1],
        [1,1,1,1,1,1,1,1],
        [1,1,1,1,1,1,1,1],
        [1,1,1,1,1,1,1,1],
        [1,1,1,1,1,1,1,1],
        [1,1,1,1,0,0,0,0]]
print(findMaxFullGrid(grid))


(2, 8, 1, 7)


In [7]:
# localize maps clients to their position in the display grid.
def localize(data, grid, name_grid):
    row = int(data[0])
    col = int(data[1])
    name = data[2]
    neighbor = data[3]
    client_id = int(data[4])
    if row > grid.shape[0]:
        padding = np.zeros((row-grid.shape[0], grid.shape[1]))
        grid = np.concatenate((grid,padding), axis=0)
        
        padding = np.empty((row-name_grid.shape[0], name_grid.shape[1]), dtype=object)
        name_grid = np.concatenate((name_grid,padding), axis=0)
    if col > grid.shape[1]:
        padding = np.zeros((grid.shape[0], col-grid.shape[1]))
        grid = np.concatenate((grid,padding), axis=1)
        
        padding = np.empty((name_grid.shape[0], col-name_grid.shape[1]), dtype=object)
        name_grid = np.concatenate((name_grid,padding), axis=1)

    if grid[row-1][col-1] != 0:
        # unsuccessful if another client is already in this position
        return grid, name_grid, False
    elif (name_grid[row-1][col-1] != None) and (name_grid[row-1][col-1] != name):
        # unsuccessful if client's name doesn't match with name already in this position
        return grid, name_grid, False
    else:
        # set client to this position
        grid[row-1][col-1] = client_id
        name_grid[row-1][col-1] = name
        # set client's neighbor's name
        if (col-1)!=0:
            name_grid[row-1][col-2] = neighbor
    return grid, name_grid, True

In [8]:
def localize_all(data_array):
    grid = np.zeros((1,1))
    name_grid = np.empty((1,1), dtype=object)
    to_place = []
    for data in data_array:
        grid, name_grid, successful = localize(data,grid,name_grid)
        if not successful:
            to_place.append(data)
    # Do something with misplaced clients
    return grid, name_grid

def parse_from_string(s):
    return s.split(";")

def parse_from_strings(S):
    data = []
    for s in S:
        data.append(parse_from_string(s))
    return data

In [11]:
s_array = ["1;2;B;A;12346",
              "3;3;C;I;12350",
              "2;1;E;None;12347",
              "2;3;D;G;12348",
              "1;3;F;B;12348",
              "2;2;G;E;12351",
              "3;2;I;H;12351",
              "3;1;H;None;12351",
              "1;1;A;None;12345"]
data_array = parse_from_strings(s_array)
grid, name_grid = localize_all(data_array)
print(grid)
print(name_grid)

[[12345. 12346. 12348.]
 [12347. 12351. 12348.]
 [12351. 12351. 12350.]]
[['A' 'B' 'F']
 ['E' 'G' 'D']
 ['H' 'I' 'C']]


In [4]:
sadness = str(hash("John Doe"))
print(sadness)
print(sadness[:-8])
print(sadness[-8:])

3752075148933176157
37520751489
33176157


In [4]:
a = "a"
b = "b"
c = "c"
print(";".join([a,b,c]))

a;b;c
